### ISSUE TITLE
Linux Executable Relies on Old libpng12

### ISSUE THREAD

**Issue by battleof3** [BartGunshot/TLOPO-Launcher#2]
Running Pop!_OS 20.04, executing ./tlopo returns

`./tlopo: error while loading shared libraries: libpng12.so.0: cannot open shared object files: No such file or directory`

All current Debian/Ubuntu based distros ship libpng16 (specifically 1.6.37) due to its increased efficiency and a [security vulnerability](http://www.libpng.org/pub/png/libpng.html) in previous versions.

Can the dependency be updated, or will users need to compile the previous version/temporarily install from backports each time they wish to use the launcher?

**Comment by battleof3** [comment]
The same can be said about the depend `libssl.so.1.0.0`, whereas current LTS is `libssl1.1`

**Comment by BartGunshot** [comment]
Unfortunately outside of my control, the actual TLOPO linux game executable is what requires these outdated dependencies, not the launcher. I'm not a TLOPO developer, I just wrote this launcher with their public API since they have a linux executable available, just not a launcher for it.

**Comment by battleof3** [comment]
I see, thank you for informing me.
